### ISSUE TITLE
Don't use `onClick` for simple links

### ISSUE THREAD

**Issue by the-kenny** [domenkozar/hydra-frontend#5]
It's rather unpleasant to use web applications that use `onClick` handlers for navigation. They don't allow for Ctrl-Click ("Open link in new tab").

Routing via URL already seems to work fine, so it's mostly a matter of replacing `onClick` in `<a>`s with a `href` to the relevant page. Maybe it's even possible to create a mapping for `Page.NewProject` etc. to a given url, making navigation type-safe.

**Comment by the-kenny** [comment]
I might want to give this a try if that's okay for you (and if I find some time)

**Comment by domenkozar** [comment]
For context:

I would like Hydra frontend to be a Single Page Application to avoid reloading unnecessary resources. Reloading the page should be supported due to previous urls nevertheless.

I think it should be possible to achieve this by combining `a href` and `onClick` where the latter would override the default behavior. Also, Browser History API should support this, example: http://html5demos.com/history/fourth

**Comment by the-kenny** [comment]
Yes of course - the `href` approach wouldn't require a reload of the page. You don't even need to use `onClick` as you can hook `popstate` and `pushstate`:

```
window.addEventListener('popstate', function(e) { window.alert(42); })
```

That and the rest of the html5 history api gives a quite powerful and seamless interface that's indistinguishable from "normal" navigation via `href`. I implemented a similar approach in ClojureScript for the company I'm working on.

**Comment by domenkozar** [comment]
`navigation` package doesn't expose listeners, but we could make a case why it's useful. I'd like to keep this pure Elm, but I'll look into these two different paths we could take here :) At the end we can define `onPageClick` that sets `href` and `onClick`.

**Comment by domenkozar** [comment]
@the-kenny I've implemented this in https://github.com/domenkozar/hydra-frontend/pull/7, but ctrl+rightclick doesn't work still. Left click -> open new window does work however.

**Comment by domenkozar** [comment]
But it also doesn't work on the history api demo http://html5demos.com/history/fourth

**Comment by domenkozar** [comment]
@the-kenny I've merged the improvement, what do you think, is it satisfactory?

**Comment by domenkozar** [comment]
Since I plan to merge #10, there's one issue regarding this issue:

There's no way to set `onPreventDefaultClick` handler for elm-mdl events currently, but see https://github.com/debois/elm-mdl/pull/179

**Comment by jb55** [comment]
@domenkozar hmm I'm a bit confused by this thread. `navigation` supports a href's just fine. The route will be parsed and urlUpdate will fire when a link is clicked, although the app I do this with uses hash-urls, not sure if that's significant.

**Comment by domenkozar** [comment]
Superseeded by https://github.com/hercules-ci/hercules, will revisit this issue in future
